# Generated by Django 6.0.2 on 2026-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("+98", "Iran (+98)"),
                    ("+1", "United States/Canada (+1)"),
                    ("+90", "Turkey (+90)"),
                    ("+971", "UAE (+971)"),
                ],
                default="+98",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=24),
        ),
    ]
