# Generated by Django 6.0.2 on 2026-02-18 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_country_code_alter_user_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                default="+98",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Country code must be in +98 format.",
                        regex="^\\+\\d{1,3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
