# Generated by Django 6.0.2 on 2026-02-18 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_country_code_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                choices=[
                    ("+98", "Iran (+98)"),
                    ("+90", "Turkey (+90)"),
                    ("+971", "UAE (+971)"),
                    ("+966", "Saudi Arabia (+966)"),
                    ("+91", "India (+91)"),
                    ("+92", "Pakistan (+92)"),
                    ("+86", "China (+86)"),
                    ("+81", "Japan (+81)"),
                    ("+82", "South Korea (+82)"),
                    ("+62", "Indonesia (+62)"),
                    ("+66", "Thailand (+66)"),
                    ("+60", "Malaysia (+60)"),
                    ("+65", "Singapore (+65)"),
                    ("+61", "Australia (+61)"),
                    ("+64", "New Zealand (+64)"),
                    ("+1", "United States/Canada (+1)"),
                    ("+52", "Mexico (+52)"),
                    ("+55", "Brazil (+55)"),
                    ("+54", "Argentina (+54)"),
                    ("+56", "Chile (+56)"),
                    ("+44", "United Kingdom (+44)"),
                    ("+49", "Germany (+49)"),
                    ("+33", "France (+33)"),
                    ("+39", "Italy (+39)"),
                    ("+34", "Spain (+34)"),
                    ("+31", "Netherlands (+31)"),
                    ("+46", "Sweden (+46)"),
                    ("+47", "Norway (+47)"),
                    ("+41", "Switzerland (+41)"),
                    ("+48", "Poland (+48)"),
                    ("+27", "South Africa (+27)"),
                    ("+20", "Egypt (+20)"),
                    ("+212", "Morocco (+212)"),
                    ("+234", "Nigeria (+234)"),
                    ("+254", "Kenya (+254)"),
                    ("+93", "Afghanistan (+93)"),
                    ("+964", "Iraq (+964)"),
                    ("+963", "Syria (+963)"),
                    ("+962", "Jordan (+962)"),
                    ("+961", "Lebanon (+961)"),
                    ("+974", "Qatar (+974)"),
                    ("+965", "Kuwait (+965)"),
                    ("+968", "Oman (+968)"),
                    ("+973", "Bahrain (+973)"),
                    ("+7", "Russia (+7)"),
                    ("+380", "Ukraine (+380)"),
                    ("+40", "Romania (+40)"),
                    ("+30", "Greece (+30)"),
                    ("+351", "Portugal (+351)"),
                    ("+32", "Belgium (+32)"),
                    ("+43", "Austria (+43)"),
                    ("+45", "Denmark (+45)"),
                    ("+358", "Finland (+358)"),
                    ("+353", "Ireland (+353)"),
                    ("+420", "Czechia (+420)"),
                    ("+36", "Hungary (+36)"),
                    ("+359", "Bulgaria (+359)"),
                    ("+57", "Colombia (+57)"),
                    ("+51", "Peru (+51)"),
                    ("+58", "Venezuela (+58)"),
                    ("+598", "Uruguay (+598)"),
                    ("+591", "Bolivia (+591)"),
                    ("+593", "Ecuador (+593)"),
                    ("+84", "Vietnam (+84)"),
                    ("+63", "Philippines (+63)"),
                    ("+880", "Bangladesh (+880)"),
                    ("+94", "Sri Lanka (+94)"),
                    ("+977", "Nepal (+977)"),
                    ("+251", "Ethiopia (+251)"),
                    ("+255", "Tanzania (+255)"),
                    ("+233", "Ghana (+233)"),
                    ("+213", "Algeria (+213)"),
                    ("+216", "Tunisia (+216)"),
                    ("+237", "Cameroon (+237)"),
                ],
                default="+98",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must contain only digits.", regex="^\\d+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
