# Generated by Django 6.0.2 on 2026-02-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField()),
                ("product_name", models.CharField(max_length=30)),
                ("product_description", models.TextField()),
                ("product_file", models.FileField(upload_to="products/%Y/%m/%d")),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
