# Generated by Django 6.0.2 on 2026-02-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product_name",
            new_name="product_title",
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="order",
            name="product_file",
            field=models.FileField(
                blank=True, null=True, upload_to="products/%Y/%m/%d"
            ),
        ),
    ]
